# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160512_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidiary',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='relationship_alt',
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='relation',
            field=models.CharField(blank=True, choices=[('', ''), ('Adh\xe9rent', 'Adh\xe9rent'), ('Membre', 'Membre'), ('Filliale', 'Filliale')], max_length=255, verbose_name="nature de l'affiliation"),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='relation_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternative nature affiliation'),
        ),
    ]
