# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_marque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marque',
            new_name='Brand',
        ),
        migrations.AddField(
            model_name='company',
            name='brand',
            field=models.ManyToManyField(blank=True, to='MAIN.Brand'),
        ),
        migrations.AddField(
            model_name='company',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='topic',
            field=models.ManyToManyField(blank=True, to='MAIN.Topic'),
        ),
        migrations.AlterField(
            model_name='person',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
