# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20160512_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('_order',), 'verbose_name': 'MARQUE'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'verbose_name': 'SOCIETE'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Employ\xe9'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('_order',), 'verbose_name': 'INDIVIDU'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('_order',), 'verbose_name': 'PRODUIT'},
        ),
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name': 'Soci\xe9t\xe9 affili\xe9e'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('_order',), 'verbose_name': 'RUBRIQUE'},
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Person', verbose_name='Employ\xe9'),
        ),
        migrations.AlterField(
            model_name='job',
            name='since',
            field=models.DateField(blank=True, null=True, verbose_name="date d'entr\xe9e en fonction"),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='intitul\xe9 du poste'),
        ),
        migrations.AlterField(
            model_name='job',
            name='until',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin de la fonction'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='relation',
            field=models.CharField(blank=True, choices=[('', '---'), ('Adh\xe9rent', 'Adh\xe9rent'), ('Membre', 'Membre'), ('Antenne', 'Antenne'), ('Antenne internationale', 'Antenne internationale'), ('Filliale', 'Filliale'), ('Agence', 'Agence'), ('F\xe9d\xe9ration r\xe9gionale', 'F\xe9d\xe9ration r\xe9gionale'), ('Chambre syndicale', 'Chambre syndicale'), ('D\xe9l\xe9gation', 'D\xe9l\xe9gation')], max_length=255, verbose_name="nature de l'affiliation"),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='relation_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='nature affiliation alternative'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='sub_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_companies', to='MAIN.Company', verbose_name='Soci\xe9t\xe9 affili\xe9e'),
        ),
    ]
