# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20160501_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='brand',
            new_name='brands',
        ),
    ]
