# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_auto_20160503_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
