# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_person_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration'),
        ),
        migrations.AddField(
            model_name='company',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration'),
        ),
        migrations.AddField(
            model_name='company',
            name='subsidiaries',
            field=models.ManyToManyField(to='MAIN.Company'),
        ),
        migrations.AddField(
            model_name='person',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration'),
        ),
        migrations.AddField(
            model_name='topic',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration'),
        ),
    ]
