# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('MAIN', '0009_auto_20160510_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('illustration', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.RenameField(
            model_name='company',
            old_name='topic',
            new_name='topics',
        ),
        migrations.AddField(
            model_name='brand',
            name='topics',
            field=models.ManyToManyField(blank=True, to='MAIN.Topic'),
        ),
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, to='MAIN.Product'),
        ),
    ]
